### ISSUE TITLE
Hud

### ISSUE THREAD

**Issue by jackel1138** [jackinloadup/lunatic-fringe#1]
Health bar
Ship's Systems
Radar

**Comment by schwal10** [comment]
Any update on adding these resources to the project?

**Comment by jackinloadup** [comment]
@schwal10 unfortunately not. Happy to review PR's though.

**Comment by jackinloadup** [comment]
@schwal10 this issue is now complete. Do you agree? May I close this?

**Comment by schwal10** [comment]
@jackinloadup I agree, this can be closed
