### ISSUE TITLE
Obtain Hammerhead sprite and sounds

### ISSUE THREAD

**Issue by jackinloadup** [jackinloadup/lunatic-fringe#13]
A call to all whom read that we are looking for video or other resources that can be used to derive the game sprites and associated sounds.

**Comment by pavellishin** [comment]
I wonder how much it would cost to find an old, working mac and an install disk for After Dark... I'd be willing to contribute.

**Comment by jackinloadup** [comment]
I think with just the disk some emulators could likely get it running. Either way first priority I suppose.

**Comment by jackel1138** [comment]
Ok guys, I've been silently watching you pick this up and work on it after it laying dormant forever. I'm the one who made the original video with jackinloadup saying we were committed to finish it (and of course we weren't lol). I'm gonna make an attempt to get Snow Leopard running in a virtual box, then run Fringe Player and record sounds for you to use. I can't code, but I can do tedious tasks like that. Updates forthcoming

**Comment by jackel1138** [comment]
Assorted sound effects attached

[Fringe Sounds.zip](https://github.com/jackinloadup/lunatic-fringe/files/8057433/Fringe.Sounds.zip)

**Comment by jackel1138** [comment]
Hammerhead weapon sprites uploaded
