### ISSUE TITLE
Bug: bullets while in the base blacks out the world

### ISSUE THREAD

**Issue by albing** [jackinloadup/lunatic-fringe#8]
Steps to reproduce:

<ol>
<li>Start game and do not move
<li>Fire a bullet or be hit by a bullet
<li><i>Bug:</i> your ship is still there and can move around and fire, but the stars, enemies, etc. are all missing
</ol>

Found in: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:32.0) Gecko/20100101 Firefox/32.0

**Comment by schwal10** [comment]
After my PR is merged, this bug should be fixed.
